name = "RegistryTw"
uuid = "673a6d95-941e-46aa-9462-ec423441fff3"
repo = "https://github.com/bgctw/RegistryTw.git"
description = "bgctw's private Julia registry"

[packages]
e455a6d6-8373-11eb-38a5-df3e63e3f6fc = { name = "MissingStrategies", path = "M/MissingStrategies" }
